package uiauto.lib.enums;

public enum ConfigType {
	APPIUM_SERVER_IPADDRESS,
	WAIT_IMPLICIT,
	WAIT_EXPLICIT,
	NODE_CONFIG_FILENAME,
	APPIUM_JSFILE_PATH,
	NODE_INSTALLED_PATH,
	CHROMEDRIVER_INSTALLED_PATH,
	DEVICENAME_TESTNG,
	DEVICE_ID,
	DEVICE_NAME,
	MOBILE_DEVICE_PLATFORM,
	PLATFORM_VERSION,
	EXECUTION_ENGR,
	REPORT_DIR,
	CONTEXT_REPORT_DIR,
	SCREENSHOT_DIR,
	RESOURCES_DIR,
	MAPS_DIR,
	BROWSER_NAME, 
	SITE_URL, 
	DESKTOP_PLATFORM,
	PLATFORM_TYPE
}
